from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from app.schemas import LoanApplicationSchema
from app.graph import compiled_graph
import json
import asyncio

app = FastAPI(
    title="Aegis: Autonomous Loan Underwriting Engine",
    description="Production-grade asynchronous multi-agent orchestration pipeline for fintech auditing.",
    version="1.0.0"
)

# Enable Cross-Origin Resource Sharing (CORS) for microservice communication
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows our Streamlit frontend on port 8501 to connect seamlessly
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

async def event_generator(validated_data: dict):
    """
    Executes the real LangGraph network asynchronously, catches 
    state mutations from each node, and streams logs via Server-Sent Events.
    """
    # 1. Initialize the central LangGraph AgentState with inputs
    initial_state = {
        "client_profile": validated_data,
        "messages": [],
        "current_node": "START",
        "underwriting_metrics": {},
        "blacklist_status": "PENDING",
        "vintage_status": "PENDING",
        "final_verdict": "PENDING",
        "execution_logs": ["System Initialization: Constructing centralized AgentState record mapping..."]
    }

    try:
        # 2. Stream the graph execution node-by-node using the async astream method
        async for event in compiled_graph.astream(initial_state):
            # The event dictionary contains the active node's name as a key 
            # and the updated dictionary fields as the value.
            for node_name, updated_state in event.items():
                
                # Extract the newly appended execution logs generated by this specific node
                new_logs = updated_state.get("execution_logs", [])
                current_active_node = updated_state.get("current_node", node_name).upper()
                
                # Send each individual text log string down the HTTP connection highway immediately
                for log in new_logs:
                    payload = {
                        "node": current_active_node,
                        "status": log
                    }
                    yield f"data: {json.dumps(payload)}\n\n"
                    
                    # Small intentional pause to let the frontend render the typewriter/scrolling effect smoothly
                    await asyncio.sleep(0.4)

    except Exception as e:
        # Capture unexpected runtime infrastructure crashes safely
        error_payload = {
            "node": "CRITICAL_PIPELINE_ERROR",
            "status": f"Fatal execution exception: {str(e)}"
        }
        yield f"data: {json.dumps(error_payload)}\n\n"

@app.post("/api/v1/underwrite")
async def run_underwriting_pipeline(application: LoanApplicationSchema):
    """
    Main API endpoint entrypoint. Validates incoming data shapes via Pydantic 
    and hands processing off to the asynchronous state engine graph stream.
    """
    try:
        # Securely export checked data values into a standard Python dict
        clean_payload = application.model_dump()
        
        # Instantiate a persistent, chunked text/event-stream transaction
        return StreamingResponse(
            event_generator(clean_payload), 
            media_type="text/event-stream"
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Internal Server ingestion failure: {str(e)}")

@app.get("/health")
def health_check():
    """Simple monitoring ping to confirm backend operational health status."""
    return {"status": "healthy", "service": "aegis-backend-engine"}